language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - "pip install pipenv"
  - "pipenv install --dev"
  - "python -m nltk.downloader all"

script:
  - "pipenv run pytest"
