startswith:
  brown:
    initial:
      allowed:
        [['a'], ['b'], ['c'], ['d'], ['e'], ['f'], ['g'], ['h'], ['i'], ['j'], ['k'], ['l'], ['m'], ['n'], ['o'],
        ['p'], ['q'], ['r'], ['s'], ['t'], ['u'], ['v'], ['w'], ['y'], ['z'], ['ex']]  # no 'x'
      pos:
        ["VBD", "NN", "JJ", "NNS", "VBZ", "VBN", "VB", "RB", "VBG", "QL", "NN-HL"]
    major_system:
      allowed:
        [['s', 'z', 'x'], ['t', 'th'], ['n'], ['m'], ['r'], ['l'], ['d'], ['c', 'k', 'g', 'q'], ['b', 'h', 'v', 'w'],
        ['p', 'f']]
      pos:
        ["VBD", "NN", "IN", "JJ", "NNS", "VBZ", "VBN", "VB", "RB", "VBG", "QL", "JJT", "NN-HL", "VBN-HL", "JJR",
        "NN$", "NNS-HL", "VBG-HL", "NNS$", "JJ-HL", "FW-NN", "FW-NNS", "NN-NC", "NN+BEZ"]
pos:
  fuzzy:
    ['N', 'P']
